services:
  fpm:
    container_name: fpm
    build:
      context: ./docker/fpm
    volumes:
      - ./:/var/www/symfony_docker

  vue:
    build:
      context: ./docker/vue
      dockerfile: Dockerfile
    container_name: vue
    expose:
      - 5173
    volumes:
      - ./vue-project:/app
    depends_on:
      - fpm

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - 1337:80
      - 1338:8080
    volumes:
      - ./:/var/www/symfony_docker
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fpm